### ISSUE TITLE
Missing Shared Library MSM8916

### ISSUE THREAD

**Issue by hpnightowl** [CypherOS/hardware_qcom_display#1]
hardware/qcom/display-caf/msm8916/libhwcomposer/../common.mk: error: "hwcomposer.msm8916 (SHARED_LIBRARIES android-arm) missing libbfqio_vendor (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:840: error: exiting from previous errors

Solution:
Needs this Commit 
https://github.com/LineageOS/android_hardware_qcom_display/commit/197a40e18b003ef8c7c5049d5b2d67fa4154f57c

**Comment by Sirhc95** [comment]
gerrit
